### ISSUE TITLE
Binding attribute, tree: commit_hash#198 error

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase-spark-connector#38] opened 2018-11-20 10:27 UTC
query:

```
SELECT * FROM (
    SELECT COUNT(c.commit_hash) AS num, c.commit_hash
    FROM ref_commits r
    INNER JOIN commits c
        ON r.repository_id = c.repository_id AND r.commit_hash = c.commit_hash
    GROUP BY c.commit_hash
) t WHERE num > 1
```
Error: 

```
Name: org.apache.spark.sql.catalyst.errors.package$TreeNodeException
Message: Binding attribute, tree: commit_hash#198
StackTrace:   at org.apache.spark.sql.catalyst.expressions.BindReferences$$anonfun$bindReference$1.applyOrElse(BoundAttribute.scala:91)
  at org.apache.spark.sql.catalyst.expressions.BindReferences$$anonfun$bindReference$1.applyOrElse(BoundAttribute.scala:90)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:266)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:256)
  at org.apache.spark.sql.catalyst.expressions.BindReferences$.bindReference(BoundAttribute.scala:90)
  at org.apache.spark.sql.execution.ProjectExec$$anonfun$5.apply(basicPhysicalOperators.scala:59)
  at org.apache.spark.sql.execution.ProjectExec$$anonfun$5.apply(basicPhysicalOperators.scala:59)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:285)
  at org.apache.spark.sql.execution.ProjectExec.doConsume(basicPhysicalOperators.scala:59)
  at org.apache.spark.sql.execution.CodegenSupport$class.consume(WholeStageCodegenExec.scala:181)
  at org.apache.spark.sql.execution.FilterExec.consume(basicPhysicalOperators.scala:85)
  at org.apache.spark.sql.execution.FilterExec.doConsume(basicPhysicalOperators.scala:206)
  at org.apache.spark.sql.execution.CodegenSupport$class.consume(WholeStageCodegenExec.scala:181)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.consume(HashAggregateExec.scala:39)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.generateResultFunction(HashAggregateExec.scala:476)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.doProduceWithKeys(HashAggregateExec.scala:649)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.doProduce(HashAggregateExec.scala:165)
  at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:88)
  at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:83)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.CodegenSupport$class.produce(WholeStageCodegenExec.scala:83)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.produce(HashAggregateExec.scala:39)
  at org.apache.spark.sql.execution.FilterExec.doProduce(basicPhysicalOperators.scala:125)
  at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:88)
  at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:83)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.CodegenSupport$class.produce(WholeStageCodegenExec.scala:83)
  at org.apache.spark.sql.execution.FilterExec.produce(basicPhysicalOperators.scala:85)
  at org.apache.spark.sql.execution.ProjectExec.doProduce(basicPhysicalOperators.scala:45)
  at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:88)
  at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:83)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.CodegenSupport$class.produce(WholeStageCodegenExec.scala:83)
  at org.apache.spark.sql.execution.ProjectExec.produce(basicPhysicalOperators.scala:35)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doCodeGen(WholeStageCodegenExec.scala:524)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:576)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:247)
  at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:337)
  at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3278)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2489)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2489)
  at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3259)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3258)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2489)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2703)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:254)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:725)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:702)
  ... 42 elided
Caused by: java.lang.RuntimeException: Couldn't find commit_hash#198 in [num#185L]
  at scala.sys.package$.error(package.scala:27)
  at org.apache.spark.sql.catalyst.expressions.BindReferences$$anonfun$bindReference$1$$anonfun$applyOrElse$1.apply(BoundAttribute.scala:97)
  at org.apache.spark.sql.catalyst.expressions.BindReferences$$anonfun$bindReference$1$$anonfun$applyOrElse$1.apply(BoundAttribute.scala:91)
  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
```

**Comment by ajnavarro** [comment] 2018-11-23 11:13
This query is on tests but slightly modified:
```sql
SELECT * FROM (
    SELECT COUNT(commit_hash) AS num, commit_hash
    FROM ref_commits r
    NATURAL JOIN commits c
    GROUP BY commit_hash
) t WHERE num > 1
```

**Comment by erizocosmico** [comment] 2018-11-28 10:35
```sql
SELECT * FROM (
    SELECT COUNT(c.commit_hash) AS num, c.commit_hash
    FROM ref_commits r
    INNER JOIN commits c
        ON r.repository_id = c.repository_id AND r.commit_hash = c.commit_hash
    GROUP BY c.commit_hash
) t WHERE num > 1
```

I copied this query from the tests and it does not work in a jupyter notebook either.

**Comment by ajnavarro** [comment] 2018-11-28 11:11
@erizocosmico if you remove the `c.` from everywhere, you can execute it.

**Comment by erizocosmico** [comment] 2018-11-28 11:12
I tried that one as well, removing all `c.`, etc and it still does not work

**Comment by mcarmonaa** [comment] 2018-12-03 09:19
I couldn't find a way to "fix" it since I believe is an optimizer's spark issue.

Funny think is that the two queries ([query 1](https://github.com/src-d/gitbase-spark-connector/blob/master/src/test/scala/tech/sourced/gitbase/spark/DefaultSourceSpec.scala#L69), [query 2](https://github.com/src-d/gitbase-spark-connector/blob/master/src/test/scala/tech/sourced/gitbase/spark/DefaultSourceSpec.scala#L83)) we have in the tests work properly but if a `df.show` is added to that tests the exception raises again.

I've found some issues on spark related to this same exception, some of them fixed some of them marked as resolved because couldn't be reproduced:
- https://issues.apache.org/jira/browse/SPARK-26041
- https://issues.apache.org/jira/browse/SPARK-22641
- https://issues.apache.org/jira/browse/SPARK-13087
- https://issues.apache.org/jira/browse/SPARK-12940
- https://issues.apache.org/jira/browse/SPARK-13480

In the [third issue](https://issues.apache.org/jira/browse/SPARK-13087
), a simple test which raised the exception by the query `SELECT floor(a) AS a, collect_set(b) FROM data GROUP BY floor(a) ORDER BY a` was added and it's supposed to work. I've added this simple test and I got the exception again.
```scala
  it should "foo" in {
    import spark.implicits._

    Seq((1, 2)).toDF("a", "b").createOrReplaceTempView("data")
    val df = spark.sql("SELECT floor(a) AS a, collect_set(b) FROM " +
      "data GROUP BY floor(a) ORDER BY a")
    df.show(20, false)
  }
```

As a work around for our queries, aliasing the `commit_hash` column in the subquery makes the query work:
```scala
  it should "work properly" in {
    val df = spark.sql(
      """
        |SELECT
        |  *
        |FROM (
        |  SELECT
        |    COUNT(c.commit_hash) as num, c.commit_hash as hash
        |  FROM
        |    ref_commits r
        |  INNER JOIN
        |    commits c
        |  ON
        |    r.repository_id = c.repository_id AND r.commit_hash = c.commit_hash
        |  GROUP BY
        |    c.commit_hash
        |) t
        |WHERE
        |  num > 1
      """.stripMargin)

    df.show(20, false)
  }
```
Output:
```sql
+---+----------------------------------------+
|num|hash                                    |
+---+----------------------------------------+
|2  |b4fe601c713d62322ecacbe402085f2a0802d89c|
|2  |817ee8ad2554200cb838313831672c981f07d869|
|2  |592484d3aaca525e50880a8afc61d58ea90f7f7f|
|2  |5ccb01393dec730aabae483b3fbd173e8c418f7a|
|2  |c2ca50b1f5622cc57582ba447a149a4ac5311675|
|2  |646957acc3ca1f9969a0b33436af371c88cb4100|
|7  |2eb6eaacdb45a28a99ed91b16f6388751412e2d2|
|7  |f1fa0c18ab2148d208920aeaa8787548ed47ae88|
|8  |54b39b8b097642542741b02201ed5d8e81834c59|
|8  |11a82fbb152eebc95baa9a50a5db059523591f7f|
|8  |41f0638ddd1d401d246e04bb4f49f20599ed7d04|
|8  |73df960e45ff0bf58865c18be43381d8f4da3d8e|
|2  |6066d76b6ceedb320419f3e475228eaa6ca3efae|
|2  |ae56613b10e508bf78157b192dd1106db7ad5d5d|
|2  |5b152e2d6631f32df988a5d0e6b9adb367b17c5a|
|10 |8a222a637efb859f2ec8ee1cc5d27a31e99c8502|
|2  |5d04c80fd1a463d0a0372868556ceb00a0be5aa2|
|2  |801f65d1522d8217964d40cc2f0acf386cfcf950|
|4  |f4604725fa7b287f1dee8d0053dfb106225b9957|
|2  |0cafd233fdb94fc7939ad4472f47ef079ffab1f9|
+---+----------------------------------------+
only showing top 20 rows

```

Though the physical plans for the failing query and the working query barely differ:
```
--- Physical Plan for the failing query (`commit_hash is NOT aliased`) ---

== Physical Plan ==
*(2) Filter (num#92L > 1)
+- *(2) HashAggregate(keys=[commit_hash#100], functions=[sum(count(commit_hash#98)#101)], output=[num#92L, commit_hash#100])
   +- Exchange hashpartitioning(commit_hash#100, 200)
      +- *(1) HashAggregate(keys=[commit_hash#100], functions=[partial_sum(count(commit_hash#98)#101)], output=[commit_hash#100, sum#103L])
         +- *(1) DataSourceV2Scan [commit_hash#100, count(commit_hash#98)#101], DefaultReader(List(GitbaseServer(localhost:3308,root,)),StructType(StructField(commit_hash,StringType,true), StructField(count(commit_hash#98),IntegerType,false)),GroupBy(List(commit_hash#98, count(commit_hash#98) AS count(commit_hash#98)#99L),ArrayBuffer(commit_hash#98),Project(List(commit_hash#9),Join(Table(ref_commits),Table(commits),Some(((repository_id#8 = repository_id#16) && (commit_hash#9 = commit_hash#17)))))))

```
```
--- Physical Plan for the working query (`commit_hash is aliased`) ---

== Physical Plan ==
*(2) Filter (num#92L > 1)
+- *(2) HashAggregate(keys=[commit_hash#101], functions=[sum(count(commit_hash#99)#102)], output=[num#92L, hash#93])
   +- Exchange hashpartitioning(commit_hash#101, 200)
      +- *(1) HashAggregate(keys=[commit_hash#101], functions=[partial_sum(count(commit_hash#99)#102)], output=[commit_hash#101, sum#104L])
         +- *(1) DataSourceV2Scan [commit_hash#101, count(commit_hash#99)#102], DefaultReader(List(GitbaseServer(localhost:3308,root,)),StructType(StructField(commit_hash,StringType,true), StructField(count(commit_hash#99),IntegerType,false)),GroupBy(List(commit_hash#99, count(commit_hash#99) AS count(commit_hash#99)#100L),ArrayBuffer(commit_hash#99),Project(List(commit_hash#9),Join(Table(ref_commits),Table(commits),Some(((repository_id#8 = repository_id#16) && (commit_hash#9 = commit_hash#17)))))))
```

**Comment by erizocosmico** [comment] 2018-12-04 14:09
Should we report this to spark, then?

**Comment by mcarmonaa** [comment] 2018-12-20 14:46
This test works properly:
```scala
  it should "get commits that appear in more than one reference" in {
    val df = spark.sql("SELECT * FROM (" +
      " SELECT COUNT(commit_hash) AS num, commit_hash" +
      " FROM ref_commits r" +
      " NATURAL JOIN commits c" +
      " GROUP BY commit_hash" +
      ") t WHERE num > 1")

    df.count() should be(1046)
    for (row <- df.collect()) {
      row.length should be(2)
    }
  }
```

but if we run the same query calling the method `show` on the Dataframe:
```scala
  it should "work properly" in {
    val df = spark.sql(
      """
        |SELECT
        |  *
        |FROM (
        |  SELECT
        |    COUNT(c.commit_hash) as num, c.commit_hash
        |  FROM
        |    ref_commits r
        |  INNER JOIN
        |    commits c
        |  ON
        |    r.repository_id = c.repository_id AND r.commit_hash = c.commit_hash
        |  GROUP BY
        |    c.commit_hash
        |) t
        |WHERE
        |  num > 1
      """.stripMargin)

    df.show(20, false)
  }
```

we get this exception:
```
org.apache.spark.sql.catalyst.errors.package$TreeNodeException: Binding attribute, tree: commit_hash#115
...
Cause: java.lang.RuntimeException: Couldn't find commit_hash#115 in [num#92L]
...
```

The problem seems to be related to our `PushDownTree` rule, specifically with this [case](https://github.com/src-d/gitbase-spark-connector/blob/master/src/main/scala/tech/sourced/gitbase/spark/rule/PushdownTree.scala#L22) on this [if-else branch](https://github.com/src-d/gitbase-spark-connector/blob/master/src/main/scala/tech/sourced/gitbase/spark/rule/PushdownTree.scala#L29).

Following the execution an attribute `commit_hash#115` never pass throw (or is produced in) this if-else branch. If the branch is commented the code works correctly.

Adding a call to `explain` before the one to `show`, we see that `commit_hash#1115` is not present in none of the plans:
```scala
...
 df.explain(true)
 df.show(20, false)
...
```
```
== Parsed Logical Plan ==
'Project [*]
+- 'Filter ('num > 1)
   +- 'SubqueryAlias t
      +- 'Aggregate ['c.commit_hash], ['COUNT('c.commit_hash) AS num#92, 'c.commit_hash]
         +- 'Join Inner, (('r.repository_id = 'c.repository_id) && ('r.commit_hash = 'c.commit_hash))
            :- 'SubqueryAlias r
            :  +- 'UnresolvedRelation `ref_commits`
            +- 'SubqueryAlias c
               +- 'UnresolvedRelation `commits`

== Analyzed Logical Plan ==
num: bigint, commit_hash: string
Project [num#92L, commit_hash#17]
+- Filter (num#92L > cast(1 as bigint))
   +- SubqueryAlias t
      +- Aggregate [commit_hash#17], [count(commit_hash#17) AS num#92L, commit_hash#17]
         +- Join Inner, ((repository_id#8 = repository_id#16) && (commit_hash#9 = commit_hash#17))
            :- SubqueryAlias r
            :  +- SubqueryAlias ref_commits
            :     +- DataSourceV2Relation [repository_id#8, commit_hash#9, ref_name#10, history_index#11L], DefaultReader(WrappedArray(GitbaseServer(localhost:3308,root,)),StructType(StructField(repository_id,StringType,true), StructField(commit_hash,StringType,true), StructField(ref_name,StringType,true), StructField(history_index,LongType,true)),Table(ref_commits))
            +- SubqueryAlias c
               +- SubqueryAlias commits
                  +- DataSourceV2Relation [repository_id#16, commit_hash#17, commit_author_name#18, commit_author_email#19, commit_author_when#20, committer_name#21, committer_email#22, committer_when#23, commit_message#24, tree_hash#25, commit_parents#26], DefaultReader(WrappedArray(GitbaseServer(localhost:3308,root,)),StructType(StructField(repository_id,StringType,true), StructField(commit_hash,StringType,true), StructField(commit_author_name,StringType,true), StructField(commit_author_email,StringType,true), StructField(commit_author_when,TimestampType,true), StructField(committer_name,StringType,true), StructField(committer_email,StringType,true), StructField(committer_when,TimestampType,true), StructField(commit_message,StringType,true), StructField(tree_hash,StringType,true), StructField(commit_parents,BinaryType,true)),Table(commits))

== Optimized Logical Plan ==
Filter (num#92L > 1)
+- Aggregate [commit_hash#101], [sum(count(commit_hash#99)#102) AS num#92L, commit_hash#101]
   +- DataSourceV2Relation [commit_hash#101, count(commit_hash#99)#102], DefaultReader(List(GitbaseServer(localhost:3308,root,)),StructType(StructField(commit_hash,StringType,true), StructField(count(commit_hash#99),IntegerType,false)),GroupBy(List(commit_hash#99, count(commit_hash#99) AS count(commit_hash#99)#100L),ArrayBuffer(commit_hash#99),Project(List(commit_hash#9),Join(Table(ref_commits),Table(commits),Some(((repository_id#8 = repository_id#16) && (commit_hash#9 = commit_hash#17)))))))

== Physical Plan ==
*(2) Filter (num#92L > 1)
+- *(2) HashAggregate(keys=[commit_hash#101], functions=[sum(count(commit_hash#99)#102)], output=[num#92L, commit_hash#101])
   +- Exchange hashpartitioning(commit_hash#101, 200)
      +- *(1) HashAggregate(keys=[commit_hash#101], functions=[partial_sum(count(commit_hash#99)#102)], output=[commit_hash#101, sum#104L])
         +- *(1) DataSourceV2Scan [commit_hash#101, count(commit_hash#99)#102], DefaultReader(List(GitbaseServer(localhost:3308,root,)),StructType(StructField(commit_hash,StringType,true), StructField(count(commit_hash#99),IntegerType,false)),GroupBy(List(commit_hash#99, count(commit_hash#99) AS count(commit_hash#99)#100L),ArrayBuffer(commit_hash#99),Project(List(commit_hash#9),Join(Table(ref_commits),Table(commits),Some(((repository_id#8 = repository_id#16) && (commit_hash#9 = commit_hash#17)))))))

```

On the other hand, adding a breakpoint just before the exception is raised [here](https://github.com/apache/spark/blob/branch-2.3/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/BoundAttribute.scala#L94) we can see that the problem is that there is no an attribute with the `commit_hash#15`'s id in the `AttributeSeq` argument given to the method [bindReference](https://github.com/apache/spark/blob/branch-2.3/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/BoundAttribute.scala#L88) just a an attribute `num#92`. Not surprisingly since there isn't an attribute `commit_hash` in our generated plans either.

Going down in the stack, we can see that when the method `show` is called on the Dataframe, a [new Dataframe](https://github.com/apache/spark/blob/branch-2.3/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L244) is instantiated with the same plans but the attribute's identifiers are modified.

Then the execution goes through [takeResult](https://github.com/apache/spark/blob/branch-2.3/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L254) in [take](https://github.com/apache/spark/blob/branch-2.3/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L2703) -> [head](https://github.com/apache/spark/blob/branch-2.3/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L254) -> [withAction](https://github.com/apache/spark/blob/branch-2.3/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L254) where the attribute's identifiers are modified again and "commit_hash#115" appears the first time.

From here the execution run until the already known exception in [bindReference](https://github.com/apache/spark/blob/branch-2.3/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/BoundAttribute.scala#L88).

**Comment by erizocosmico** [comment] 2018-12-21 10:13
Do you need help with this issue @mcarmonaa?

**Comment by mcarmonaa** [comment] 2018-12-21 11:16
Yes, it would be great @erizocosmico

**Closed** 2019-01-14 09:40 UTC
Labels: bug
